general.import = [
        # color themes
        #"~/.config/alacritty/github-dark-high-contrast.toml"
        #"~/.config/alacritty/pride-colours.toml"
        #"~/.config/alacritty/shades-of-purple-default.toml"
        "~/.config/alacritty/shades-of-purple-super-dark.toml"
        #"~/.config/alacritty/tokyo-night-default.toml"
        #"~/.config/alacritty/github-dark-high-contrast.toml"
]

[env]
TERM = "xterm-256color"
WINIT_X11_SCALE_FACTOR = "1"

[window]
dynamic_padding = true
decorations = "full"
title = "Alacritty@CachyOS"
opacity = 0.8
decorations_theme_variant = "Dark"

[window.dimensions]
columns = 100
lines = 30

[window.class]
instance = "Alacritty"
general = "Alacritty"

[scrolling]
history = 10000
multiplier = 3

[font]
size = 16

[font.normal]
family = "jetbrainsmono nerd font"
style = "regular"


