icons_format = "{icon}"

[theme]
theme = "ctp-mocha"
[theme.overrides]
#idle_bg = "#123456"
#idle_fg = "#abcdef"

[icons]
icons = "awesome6"
[icons.overrides]
bat = ["|E|", "|_|", "|=|", "|F|"]
bat_charging = "|^| "

[[block]]
block = "music"
format = "{$combo.str(max_w:25,rot_interval:0.5) $prev $play $next|}"
separator = "|"

[[block]]
block = "cpu"
info_cpu = 40
warning_cpu = 70
critical_cpu = 90


#[[block]]
#block = "disk_space"
#path = "/"
#info_type = "available"
#alert_unit = "GB"
#interval = 20
#warning = 20.0
#alert = 10.0
#format = " $icon root: $available.eng(w:2) "

[[block]]
block = "memory"
format = " $icon$mem_used"
format_alt = " $icon_swap$swap_used"


[[block]]
block = "sound"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 5
format = "$timestamp.datetime(f:'%d/%m/%y %R') "
