icons_format = "{icon}"

[theme]
theme = "ctp-mocha"
[theme.overrides]
idle_bg = "#24273a"
#idle_fg = "#abcdef"

[icons]
icons = "material-nf"
[icons.overrides]
bat = ["|E|", "|_|", "|=|", "|F|"]
bat_charging = "|^| "

[[block]]
block = "music"
format = "{$combo.str(max_w:35,rot_interval:0.3) $prev $play $next|}"
separator = "|"

[[block]]
block = "amd_gpu"
format = " $icon $utilization "
format_alt = " $icon MEM: $vram_used_percents ($vram_used/$vram_total) "
interval = 1

[[block]]
block = "cpu"
info_cpu = 40
warning_cpu = 70
critical_cpu = 90


[[block]]
block = "pomodoro"
notify_cmd = "notify-send '{msg}'"
blocking_cmd = false

#[[block]]
#block = "disk_space"
#path = "/"
#info_type = "available"
#alert_unit = "GB"
#interval = 20
#warning = 20.0
#alert = 10.0
#format = " $icon root: $available.eng(w:2) "

[[block]]
block = "memory"
format = "$icon $mem_used"
format_alt = " $icon_swap$swap_used"


[[block]]
block = "sound"
driver = "auto"
format = "$icon $volume"
[[block.click]]
button = "left"
cmd = "pavucontrol"

[[block]]
block = "time"
interval = 5
format = "$timestamp.datetime(f:'%d/%m/%y %R') "

