#config location:
# ~/.config/mpd/mpd.conf

music_directory "/home/sandil/Music/"
playlist_directory "/home/sandil/Music/Playlists"

auto_update "yes"
auto_update_depth "0"
bind_to_address "127.0.0.1"
max_output_buffer_size "16384"
restore_paused "yes"

audio_output {
    type "pipewire"
    name "pipeWire output"
}
